---
abstract: 'parse and interact with a NetHack item'
author:
  - 'Shawn M Moore <sartak@bestpractical.com>'
  - 'Jesse Luehrs <doy at tozt dot net>'
  - 'Sean Kelly <cpan@katron.org>'
  - "Stefan O'Rear <stefanor@cox.net>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetHack-Item
requires:
  Module::Pluggable: 3.8
  Moose: 0.90
  MooseX::Role::Parameterized: 0.05
  NetHack::Monster::Spoiler: 0.02
  Set::Object: 1.00
  Test::Fatal: 0.007
  Test::More: 0.88
version: 0.21
