---
abstract: 'parse and interact with a NetHack item'
author:
  - 'Shawn M Moore, C<< <sartak@gmail.com> >>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: NetHack-Item
no_index:
  directory:
    - inc
    - t
requires:
  Module::Pluggable: 0
  Moose: 0.54
  MooseX::AttributeHelpers: 0.12
version: 0.01
