--- 
abstract: parse and interact with a NetHack item
author: 
  - Shawn M Moore <sartak@bestpractical.com>
  - Jesse Luehrs <doy@tozt.net>
  - Sean Kelly <cpan@katron.org>
  - Stefan O'Rear <stefanor@cox.net>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: NetHack-Item
requires: 
  Module::Pluggable: 3.8
  Moose: 0.54
  MooseX::AttributeHelpers: 0.12
  NetHack::Monster::Spoiler: 0.02
  Set::Object: 1.00
  Test::Exception: 0.27
  Test::More: 0.86
version: 0.09
