---
abstract: 'parse and interact with a NetHack item'
author:
  - 'Shawn M Moore, C<sartak@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetHack-Item
no_index:
  directory:
    - inc
    - t
requires:
  Module::Pluggable: 3.8
  Moose: 0.9
  MooseX::Role::Parameterized: 0.05
  NetHack::Monster::Spoiler: 0.02
  Set::Object: 1
  Test::Exception: 0.27
  Test::More: 0.86
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
