--- 
abstract: parse and interact with a NetHack item
author: 
  - Shawn M Moore <sartak@bestpractical.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: NetHack-Item
requires: 
  Log::Dispatch: 2.22
  Module::Pluggable: 3.8
  Moose: 0.54
  MooseX::AttributeHelpers: 0.12
  Net::Twitter: 1.17
  Set::Object: 1.00
  Test::Exception: 0.27
  Test::More: 0.86
version: 0.05
